version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: web-portfolio
    ports:
      - "3000:3000"
    restart: always
    read_only: true
    volumes:
      - .:/app
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
    networks:
      - web
networks:
  web:
    driver: bridge